const SOCKET_CLIENT_SEND_PROFILE = "SOCKET_CLIENT_SEND_PROFILE";

const SOCKET_CLIENT_SEND_NEW_POST = "SOCKET_CLIENT_SEND_NEW_POST";
const SOCKET_SERVER_SEND_NEW_POST = "SOCKET_SERVER_SEND_NEW_POST";

module.exports = {
	SOCKET_CLIENT_SEND_PROFILE,
	SOCKET_CLIENT_SEND_NEW_POST,
	SOCKET_SERVER_SEND_NEW_POST,
};
